#!/bin/sh

SRCDIR="src"
BUILDDIR="build"
TESTDIR="tests"

CC="${CC:-gcc}"
LD="${LD:-ld}"
BUILDFLAGS="$CFLAGS $(tr '\n' ' ' < compile_flags.txt)"

get_files() {
	find $1 -type f -exec basename {} \;
}

build_f() {
	src=$1 obj=$2 opts=$3

	src_time=$(stat -c "%Y" "$src")
	obj_time=$(stat -c "%Y" "$obj" 2> /dev/null || echo 0)

	[ -f "$obj" ] && [ $obj_time -ge $src_time ] && return 69 || {
		cmd="$CC $BUILDFLAGS $opts -o $obj $src"
		echo $cmd; $cmd
	}
}

build_dir() {
	dir=$1 opts=$2 objext=$3

	objdir="$BUILDDIR/$dir"
	changed=1

	mkdir -p $objdir

	for src in $(get_files $dir); do
		build_f "$dir/$src" "$objdir/${src%.*}$objext" "$opts"
		[ $? -ne 69 ] && { [ $? -eq 0 ] && changed=0 || exit $?; }
	done

	return $changed
}

case $1 in
	"clean") rm -r $BUILDDIR ;;
	"test")
		for t in build/tests/*; do
			LD_LIBRARY_PATH=$LD_LIBRARY_PATH:build $t
		done
		;;

	"tests")
		build_dir $TESTDIR "-Lbuild -lprism" ""
		;;

	"lib")
		build_dir $SRCDIR "-c" ".o"
		changed=$?

		[ $changed -ne 0 ] && [ -f "$BUILDDIR/main" ] || {
			objs=$(get_files $SRCDIR | sed "s|\(.*\)\.[^.]*|$BUILDDIR/$SRCDIR/\1.o|")
			cmd="$LD -shared -o $BUILDDIR/libprism.so $objs"
			echo $cmd; $cmd
		}
		;;

	*)
		$0 lib
		$0 tests
esac
